### ISSUE TITLE
"TypeError: Spread syntax requires ...iterable not be null or undefined" when theme-color metatag not using `rgb()`

### ISSUE THREAD

**Issue by eden-chan** [silk-hq/community#18]
My silk sheet in my deployed project is failing to load only on my mobile device, and renders as "Something went wrong"
Note, the deployed project silk component works perfectly fine on my desktop, in mobile view but fails to load on my actual mobile device. 

I found the fix tho! 
This is due to {...restProps} not having a fallback of {...(restProps || {})} in the example component definitions of the [example silk components](https://github.com/silk-hq/basic-examples-css) with `{...(restProps || {})}`

I inspected my safari mobile debug logs with my Mac and see this: 

![Image](https://github.com/user-attachments/assets/f41fd953-3f3c-4f20-9444-21be304e8e8a)

![Image](https://github.com/user-attachments/assets/96f4f2c9-8e6e-49e0-831b-3a52d29a1c58)

![Image](https://github.com/user-attachments/assets/703f5bfc-f23a-4d7e-8cc7-f9519d9128ac)

<img width="233" alt="Image" src="https://github.com/user-attachments/assets/666742aa-80ec-41f7-afe2-600e5ee80656" />

Attached is the minified code in the image https://gist.github.com/eden-chan/fec8a7be1cbb322f924994ff41b9273c

![Image](https://github.com/user-attachments/assets/836b7789-37e1-446b-afca-e2ecb5c10e6c)

**Comment by maxsalven** [comment]
Spreading `undefined` is fine:
```js
> {...undefined}
{}
```

Could this be a dupe of https://github.com/silk-hq/community/issues/13?

**Comment by brunostasse** [comment]
I am not certain when this problem arises, as I can't reproduce it myself.

Any chance you could provide a reproduction in a CodeSandbox @eden-chan?

**Comment by brunostasse** [comment]
> Could this be a dupe of [#13](https://github.com/silk-hq/community/issues/13) which similarly only impacts Safari?

Good catch @maxsalven. It actually happens when the theme-color is set to a value that doesn't use the `rgb()` form (e.g. using the hexadecimal syntax).

I will throw a proper error in this case.

**Comment by brunostasse** [comment]
A proper error is now thrown with the version 0.8.14 that I just published.

If you can test and let me know if it works for you that'd be great!

[See changelog for 0.8.14](https://silkhq.notion.site/Changelog-1c8894277f3a80769653fbdca61da4d7).

**Comment by brunostasse** [comment]
Closing this issue as it is now resolved.

**Comment by mortenbo** [comment]
@brunostasse Hi. I think it may not be fixed (or it's a new one). We get this error quite a lot in production for the latest version of Silk:

<img width="709" height="192" alt="Image" src="https://github.com/user-attachments/assets/d993bd1a-774f-48c9-8e7e-4714e8b9c4fc" />

This is the code that fails. I assume it's inside Silk:

<img width="1048" height="108" alt="Image" src="https://github.com/user-attachments/assets/8542073c-ebd4-4181-afcf-3442f7980834" />

Our theme-color setup:

<img width="432" height="213" alt="Image" src="https://github.com/user-attachments/assets/25520ac8-231d-4e17-9261-3ddc9cf94448" />

**Comment by brunostasse** [comment]
Hi @mortenbo, looking at the error stack I see you're using Capacitor. Looking at the docs it seems the `theme-color` meta tag is not supported in that context, which may explain the error. I'll ship a change tomorrow to try and fix it.

**Comment by mortenbo** [comment]
@brunostasse Nice, thank you. It does seem to work in most cases but we get this error in some rare cases I can't reproduce. We get the error around 1,000 times per day.

**Comment by brunostasse** [comment]
@mortenbo I just published an update (v0.10.0) that makes `theme-color` meta tag manipulations safer in context that may not be able to define the meta tag. Can you try to update and let me know if that fix the error?

Note that the update contains a breaking change regarding the `exitingAnimationSettings` prop's `contentMove` option.

See the changelog [here](https://github.com/silk-hq/silk/blob/main/CHANGELOG-LIBRARY.md).

**Comment by mortenbo** [comment]
@brunostasse Sweet. Will deploy to production within the hour and get back to you within 1-2 days when I can see the new error logs.

**Comment by mortenbo** [comment]
@brunostasse I'll get back to you Monday instead. I don't have enough data to confirm it's working (native apps are a bit delayed). It looks like the error rate is dropping but I'm not sure yet.

**Comment by brunostasse** [comment]
@mortenbo Alright, let me know where you're sure!

**Comment by mortenbo** [comment]
I'm not 100% but I don't think it's solved yet. 

<img width="703" height="193" alt="Image" src="https://github.com/user-attachments/assets/36daa27a-f0c4-4ae0-b51d-b61023b85850" />
<img width="469" height="167" alt="Image" src="https://github.com/user-attachments/assets/14c808aa-0f0a-409f-823c-7d68c162ac3c" />

It must be this part; `let n=[...e]`.

**Comment by brunostasse** [comment]
Yes, this is the part I addressed with the update.

If it didn't work I'll have to set up a Capacitor environment and try to reproduce it.

**Comment by mortenbo** [comment]
I don't think it's fixed, I'm afraid. And I'm not able to reproduce in Capacitor myself. It happens in some rare cases.

I think it's related to returning to the app after a period of inactivity. The error only happens on iOS and could be related to https://developer.apple.com/documentation/webkit/wknavigationdelegate/webviewwebcontentprocessdidterminate(_:)

**Comment by kryali** [comment]
just got a "Spread syntax..." exception from an ios user. @brunostasse is this the same issue reported or a different one?

library version: `@silk-hq/components@^0.10.0`
user agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 18_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148`

for context, my site is deployed in a native iOS app using WKWebView
```
TypeError: Spread syntax requires ...iterable not be null or undefined
    at q (../node_modules/@silk-hq/components/dist/module.mjs:3:6999)
    at eH.setActualThemeColor (../node_modules/@silk-hq/components/dist/module.mjs:3:34068)
    at eH.updateThemeColorDimmingOverlayAlphaValue (../node_modules/@silk-hq/components/dist/module.mjs:3:34702)
    at a (../node_modules/@silk-hq/components/dist/module.mjs:3:111196)
    at a (../node_modules/@silk-hq/components/dist/module.mjs:3:53439)
    at e (../node_modules/@silk-hq/components/dist/module.mjs:3:53200)
    at sentryWrapped (../node_modules/@sentry/browser/build/npm/esm/helpers.js:93:17)
```
upgraded to 0.10.0 on nov5

<img width="1023" height="426" alt="Image" src="https://github.com/user-attachments/assets/9aad4510-c467-497e-b8b2-3fef8a5f1afd" />

some AI suggestion:
<img width="817" height="431" alt="Image" src="https://github.com/user-attachments/assets/2cd4a344-7e01-4db1-a351-6e94c755e3ac" />

**Comment by brunostasse** [comment]
@kryali This does indeed look like the same problem, especially as it arises in the context of WKWebView as well. I'll have another go at it in the next few weeks.

In the meantime the suggestion you got should indeed work. If you're only using Silk in the context of WKWebView, removing the `themeColorDimming` prop should remove the error. If you're also using it in the context of Safari, you can detect in what context you are and not use the prop inside of WKWebView.

**Comment by mortenbo** [comment]
Removing themeColorDimming or setting to false fixes the TypeError in production for us. However, it does seem like the backdrop fade in animation is more abrupt/faster. Is that correct?

**Comment by brunostasse** [comment]
> However, it does seem like the backdrop fade in animation is more abrupt/faster. Is that correct?

Good catch. There is indeed a difference when `themeColorDimming` is in effect and when it is not. When used, the backdrop's opacity animation is run on the main thread, on the CPU, when it's not used it is run on the GPU (the animation is "hardware-accelerated"). Usually GPU-run animations perform better, because they can't be interrupted by other work performed on the main thread, and because main-thread animations are actually capped by Apple at 60fps, whereas GPU ones are not, so they can go up to 120fps.

Here you're seeing a degradation of the performance when the animation is run on the GPU though. My observation is that GPU-run animations drop frames in WebKit at the beginning of the animation, making them feel "abrupt". I believe this has deteriorated further about a year ago. In my tests they still overall perform better than on the CPU, because they're less prone to mid-flight interruptions, and still have a higher frame rate. That's why I still opt in when possible. I have also implemented several optimizations to get the best performance possible out of them.

Apple has been working on [a big architectural change](https://bugs.webkit.org/show_bug.cgi?id=250970) regarding how they run animations on the GPU for several years. My hope is that the performance will improve when this change ships, hopefully matching that of Chromium.

In the meantime, regarding this specific animation, if you prefer to keep the animation run on the CPU (as it is when using `themeColorDimming`), you can disable the default `travelAnimation` on `<Sheet.Backdrop>` by passing `{ opacity: null }` to it, and animate the opacity using the `onTravel` prop on `<Sheet.View>`. Animations driven by the `progress` value in this prop perform on the CPU. Note that it would then likely not perform as well in other browsers, so you probably want to do that only on iOS.

**Comment by mortenbo** [comment]
Thank you very much for that elaborate answer! I very much look forward to the WebKit improvement as it's a recurring issue. And thanks for the alternative solution. I think I'll keep using the GPU optimized animation for now but I very much appreciate the explanation for why they behave differently.
